"""Conversation trace generator.

Produces multi-session traces from a Persona. Sessions are generated by
running a "user simulator" LLM driven by the persona's disclosure plan,
and a stand-in agent. Traces are deterministic given (persona, seed,
generator_version).

See SPEC.md §5.
"""

GENERATOR_VERSION = "v1"
